---
conf:
  tftp_boot_dir: /var/lib/tftpboot
  http_root_dir: /var/www/html
#
# For each subnet we need the subnet id. There are 6 needed subnets: 
#  'admin', 'public_floating', 'public_api', 'cloud_sdn', 'storage_repl', 'storage_client'
#
subnets:
  admin: @admin_subnet@
  public_floating: @public_floating_subnet@
  public_api: @public_api_subnet@
  cloud_sdn: @cloud_sdn_subnet@
  storage_repl: @storage_repl_subnet@
  storage_client: @storage_client_subnet@

images:
  - name: SLE12_SP3
    title: SUSE Linux Enterprise Server 12 - SP3
    file_url: http://myserver.com/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
    #md5_url: http://myserver.com/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso.md5          # optional, either md5_url or md5_must be specified
    md5_value: 633537da81d270a9548272dfe1fdd20d                                   # optional, either md5_url or md5_must be specified
    filename: SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
    save_dir: /root/images                                                         # Directory specified here must exist on bootserver
    mount_point: SLE12_SP3                                                         # appended to the value of 'http_root_dir'
  - name: SLE12_SP2
    title: SUSE Linux Enterprise Server 12 - SP2
    file_url: http://myserver.com/SLE-12-SP2-Server-DVD-x86_64-GM-DVD1.iso
    #md5_url: http://myserver.com/SLE-12-SP2-Server-DVD-x86_64-GM-DVD1.iso.md5          # optional, either md5_url or md5_must be specified
    md5_value: fe01223a08b2d293da2f940658af8168                                   # optional, either md5_url or md5_must be specified
    filename: SLE-12-SP2-Server-DVD-x86_64-GM-DVD1.iso
    save_dir: /root/images                                                         # Directory specified here must exist on bootserver
    mount_point: SLE12_SP2                                                         # appended to the value of 'http_root_dir'

machines:
  - tag: kvm
    image: SLE12_SP3
    yast_template: autoyast_kvmhost.xml     # In the <root_dir>/yast_templates folder
  - tag: compute
    image: SLE12_SP2
    yast_template: autoyast_compute.xml     # In the <root_dir>/yast_templates folder
  
